[package]
name = "invisibility"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-service = "2.0.2"
actix-web = "4.3.1"
anyhow = "1.0.80"
async-openai = { git = "https://github.com/djmango/async-openai.git", branch = "master" }
# async-openai = { path = "../async-openai/async-openai/" }
async-stripe = { version = "0.34.1", features = ["runtime-tokio-hyper"] }
bytes = "1.5.0"
chrono = "0.4.34"
convert_case = "0.6.0"
futures = "0.3.30"
futures-util = "0.3.30"
jsonwebtoken = "9.2.0"
maplit = "1.0.2"
once_cell = "1.19.0"
rand = "0.8.5"
reqwest = { version = "0.11.24", features = ["json"] }
sea-query = "0.30.7"
sentry = "0.32.2"
sentry-actix = "0.32.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
shuttle-actix-web = "0.44.0"
shuttle-aws-rds = "0.44.0"
shuttle-persist = "0.44.0"
shuttle-runtime = "0.44.0"
thiserror = "1.0.57"
# tokenizers = { version = "0.15.2", features = ["http"] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.40"
