[package]
name = "invisibility"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-service = "2.0.2"
actix-web = "4.3.1"
anyhow = "1.0.80"
async-openai = "0.18.3"
bytes = "1.5.0"
chrono = "0.4.34"
color-eyre = "0.6.2"
futures = "0.3.30"
futures-util = "0.3.30"
jsonwebtoken = "9.2.0"
once_cell = "1.19.0"
rand = "0.8.5"
reqwest = "0.11.24"
serde = {version = "1.0.197", features = ["derive"]}
serde_json = "1.0.114"
shuttle-actix-web = "0.40.0"
shuttle-runtime = "0.40.0"
shuttle-secrets = "0.40.0"
thiserror = "1.0.57"
tokio = "1.26.0"
tracing = "0.1.40"
