[package]
name = "invisibility"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-service = "2.0.2"
actix-web = "4.3.1"
anyhow = "1.0.80"
async-openai = "0.18.3"
async-stripe = { version = "0.34.1", features = ["runtime-tokio-hyper"] }
aws-config = { version = "1.1.7", features = ["behavior-version-latest"]  }
aws-sdk-bedrockruntime = "1.16.0"
aws-smithy-runtime-api = "1.1.7"
bytes = "1.5.0"
chrono = "0.4.34"
color-eyre = "0.6.2"
convert_case = "0.6.0"
futures = "0.3.30"
futures-util = "0.3.30"
jsonwebtoken = "9.2.0"
once_cell = "1.19.0"
rand = "0.8.5"
reqwest = "0.11.24"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
shuttle-actix-web = "0.41.0"
shuttle-persist = "0.41.0"
shuttle-runtime = "0.41.0"
shuttle-secrets = "0.41.0"
thiserror = "1.0.57"
# tokenizers = { version = "0.15.2", features = ["http"] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.40"
