[package]
name = "invisibility"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
anyhow = "1.0.80"
async-openai = "0.18.3"
bytes = "1.5.0"
color-eyre = "0.6.2"
futures = "0.3.30"
rand = "0.8.5"
shuttle-actix-web = "0.39.0"
shuttle-runtime = "0.39.0"
shuttle-secrets = "0.39.0"
tokio = { version = "1.26.0", features = ["full", "time"] }
tracing = "0.1.40"
